Change default behaviour on MetaDataException (#90)
Error occurs when tenant or namespace does not exist.
org.apache.pulsar.broker.web.RestException: Policies not found for tenant/namespace namespace